### ISSUE TITLE
Coding-Style

### ISSUE THREAD

**Issue by Fawkes-c** [williamdev/WebWareBox#1]
Okay. So, for all of the Source-Code to be easily read, understood and consistent, we need a Coding-Style(**Or 'Indentation-Style'**).

This Coding-Style will apply to the following things:

- Indentation(**Will we use Spaces or Tabs? How many Spaces will we use?**)
- Spacing(**So, there is Spacing between Operators and Variables**)
- Function/Class/Variable-Names(**How long should the Name of a Variable be? How constructive should they be?**)
- Maximum Line-Length(**Should Lines only be 80 Columns? What about 100 or 120 Columns?**)
- Comments(**When should a Comment be used and not be used?**)

If we establish a Coding-Style, the Source-Code can easily be read and understood and also be consistent across all Files. If we don't then it can cause issues with consistency and some may find the Code to be hard to read if there's too many different Styles.

If you'd like, we can also go ahead and use Python's PEP 8 Standard(_https://www.python.org/dev/peps/pep-0008/_).

**Comment by williamdev** [comment]
PEP 8 Standard seems fine.
