### ISSUE TITLE
Create Development-Branch

### ISSUE THREAD

**Issue by Fawkes-c** [williamdev/WebWareBox#2]
It would be best if we had a _Development-Branch_. One where all of the Development happens. Then once we've done some Development for a new Version of the Software, the changes can be merged into the _Master-Branch_ and the new Version can be bundled and released.

Maybe create two Development-Branches. One for Design and one for Features/Functionality. This means that Design and Functionality don't clash during Development.

**Comment by williamdev** [comment]
I can do that

**Comment by williamdev** [comment]
I have created the dev branch
